version: "2"
services:
  teampass:
    image: teampass/teampass:latest
    ports:
      - "3002:80"
      - "3003:443"
    links:
      - mysql
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
